ENH: Open all in pager via -a|--all
Useful for withDebug -s|--to-separate-files

System-info: Ubuntu 20.04.6 LTS, x86_64
Platform-info: bash 5.0.17(1)-release

diff --git a/bin/debug-recall b/bin/debug-recall
--- a/bin/debug-recall
+++ b/bin/debug-recall
@@ -19,14 +19,34 @@ HELPTEXT
     echo
     printf 'Usage: %q %s\n' "$(basename "$1")" '[-?|-h|--help]'
     echo
+    cat <<HELPTEXT
+Open all debug log files used by withDebug (last modified first) in the pager.
+HELPTEXT
+    echo
+    printf 'Usage: %q %s\n' "$(basename "$1")" '-a|--all'
+    echo
     debugRecall --help
 }
 
+typeset -a pager=("${PAGER:-less}" --RAW-CONTROL-CHARS); [ -t 1 ] || pager=(cat)
+action=
 case "$1" in
     --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
+    --all|-a)		shift; action=pageAll;;
 esac
 
-if [ $# -eq 0 ]; then
+pageAll()
+{
+    readarray -t filespecsByCreation < <(ls -1 --sort=time "$DEBUG_LOGDIR"/*)
+    if [ ${#filespecsByCreation[@]} -eq 0 ]; then
+	echo >&2 'ERROR: No debug log files found.'
+	exit 1
+    fi
+
+    exec "${pager[@]}" -- "${filespecsByCreation[@]}"
+}
+
+if [ -z "$action" -a $# -eq 0 ]; then
     DATA_DIRSPEC="${XDG_DATA_HOME:-${HOME}/.local/share}"
     WITHDEBUG_LASTLOG_FILESPEC="${DATA_DIRSPEC}/withDebug-last-log"
     lastDebugLogFilespec=; [ -r "$WITHDEBUG_LASTLOG_FILESPEC" ] \
@@ -34,7 +54,6 @@ if [ $# -eq 0 ]; then
 	&& [ -r "$lastDebugLogFilespec" ] \
 	|| exit 1
 
-    typeset -a pager=("${PAGER:-less}" --RAW-CONTROL-CHARS); [ -t 1 ] || pager=(cat)
     exec "${pager[@]}" "$lastDebugLogFilespec"
 else
     if [ ! -d "$DEBUG_LOGDIR" ]; then
@@ -42,5 +61,5 @@ else
 	exit 5
     fi
 
-    debugRecall "$@"
+    ${action:-debugRecall} "$@"
 fi
