ENH: Delegate to file-recall for recall by number or pattern
System-info: Ubuntu 20.04.6 LTS, x86_64
Platform-info: bash 5.0.17(1)-release

diff --git a/bin/debug-recall b/bin/debug-recall
--- a/bin/debug-recall
+++ b/bin/debug-recall
@@ -1,5 +1,16 @@
 #!/bin/bash
 
+: ${DEBUG_LOGDIR="${XDG_RUNTIME_DIR:-/tmp}/debug"}
+
+debugRecall()
+{
+    FILERECALL="$(basename -- "$0")" \
+    FILERECALL_BASEDIR="$DEBUG_LOGDIR" \
+    FILERECALL_WHAT='debug log' \
+    FILERECALL_OFFER_SUBDIRS='' \
+	exec file-recall "$@"
+}
+
 printUsage()
 {
     cat <<HELPTEXT
@@ -7,18 +18,29 @@ Open the last debug log used by withDebug in the pager.
 HELPTEXT
     echo
     printf 'Usage: %q %s\n' "$(basename "$1")" '[-?|-h|--help]'
+    echo
+    debugRecall --help
 }
 
 case "$1" in
     --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
 esac
 
-DATA_DIRSPEC="${XDG_DATA_HOME:-${HOME}/.local/share}"
-WITHDEBUG_LASTLOG_FILESPEC="${DATA_DIRSPEC}/withDebug-last-log"
-lastDebugLogFilespec=; [ -r "$WITHDEBUG_LASTLOG_FILESPEC" ] \
-    && <"$WITHDEBUG_LASTLOG_FILESPEC" IFS=$'\n' read -r lastDebugLogFilespec \
-    && [ -r "$lastDebugLogFilespec" ] \
-    || exit 1
+if [ $# -eq 0 ]; then
+    DATA_DIRSPEC="${XDG_DATA_HOME:-${HOME}/.local/share}"
+    WITHDEBUG_LASTLOG_FILESPEC="${DATA_DIRSPEC}/withDebug-last-log"
+    lastDebugLogFilespec=; [ -r "$WITHDEBUG_LASTLOG_FILESPEC" ] \
+	&& <"$WITHDEBUG_LASTLOG_FILESPEC" IFS=$'\n' read -r lastDebugLogFilespec \
+	&& [ -r "$lastDebugLogFilespec" ] \
+	|| exit 1
 
-typeset -a pager=("${PAGER:-less}" --RAW-CONTROL-CHARS); [ -t 1 ] || pager=(cat)
-exec "${pager[@]}" "$lastDebugLogFilespec"
+    typeset -a pager=("${PAGER:-less}" --RAW-CONTROL-CHARS); [ -t 1 ] || pager=(cat)
+    exec "${pager[@]}" "$lastDebugLogFilespec"
+else
+    if [ ! -d "$DEBUG_LOGDIR" ]; then
+	echo >&2 'ERROR: No debug log directory found.'
+	exit 5
+    fi
+
+    debugRecall "$@"
+fi
