WIP: Delegate usage to echotrace / verbose which now offer short and long usage access
System-info: Ubuntu 20.04.6 LTS, x86_64
Platform-info: bash 5.0.17(1)-release

diff --git a/bin/echotrace b/bin/echotrace
--- a/bin/echotrace
+++ b/bin/echotrace
@@ -6,12 +6,59 @@ shopt -qs extglob
 
 readonly scriptName="$(basename -- "${BASH_SOURCE[0]}")"
 
+getShortUsage()
+{
+    local usageSep
+    [ $# -gt 0 ] || set -- ''
+    while [ $# -gt 0 ]
+    do
+	local hadTopic=
+	case "$1" in
+	    ''|general) printf %s "${usageSep}${hadTopic:+ }" '[--eval]'; hadTopic=t;;&
+	    ''|debug)
+		[ -n "$1" ] \
+		    && local format='%s%s' \
+		    || local format='%s[%s]'
+		printf "$format" "${usageSep}${hadTopic:+ }" '--for DEBUGGEE [-m|--module MODULE]'; hadTopic=t;;&
+	    *)  [ "$hadTopic" ] || { echo "ERROR: Unknown short usage topic \"$1\"!" >&2; return 2; };;
+	esac
+	shift; usageSep=' '
+    done
+}
+getLongUsage()
+{
+    [ $# -gt 0 ] || set -- ''
+    while [ $# -gt 0 ]
+    do
+	local topic="$1"; shift
+	local hadTopic=
+	case "$topic" in
+	    ''|general)
+		cat <<HELPTEXT
+    --eval		Print the evaluation result instead of the (quoted)
+			eval.
+HELPTEXT
+		hadTopic=t
+		;;&
+	    ''|debug)
+		cat <<HELPTEXT
+    --for DEBUGGEE	Target DEBUGGEE; by default it will take the name of the
+			parent process.
+    --module|-m MODULE	Activate only if debugging for MODULE of the DEBUGGEE is
+			enabled.
+HELPTEXT
+		hadTopic=t
+		;;&
+	    *)  [ "$hadTopic" ] || { echo "ERROR: Unknown long usage topic \"$topic\"!" >&2; return 2; };;
+	esac
+    done
+}
 printShortUsage()
 {
     # Note: short followed by long option; if the user knows the short one, she can
     # skim the long one.
-    printf 'Usage: [ECHOTRACE_IFS=STRING|newline] [ECHOTRACE_SINK=FILESPEC|&N] %q %s\n' "$(basename "$1")" '[--eval] [--] COMMAND [...] [-?|-h|--help]'
-    printf 'Usage: ${DEBUG:+[env ECHOTRACE_IFS=STRING|newline] [(ECHOTRACE|DEBUG)_SINK=FILESPEC|&N] %q %s} %s\n' "$(basename "$1")" '[--eval] --for DEBUGGEE [-m|--module MODULE] [--]' 'COMMAND [...]'
+    printf 'Usage: [ECHOTRACE_IFS=STRING|newline] [ECHOTRACE_SINK=FILESPEC|&N] %q %s\n' "$(basename "$1")" "$(getShortUsage general) [--] COMMAND [...] [-?|-h|--help]"
+    printf 'Usage: ${DEBUG:+[env ECHOTRACE_IFS=STRING|newline] [(ECHOTRACE|DEBUG)_SINK=FILESPEC|&N] %q %s} %s\n' "$(basename "$1")" "$(getShortUsage general) $(getShortUsage debug) [--]" 'COMMAND [...]'
 }
 printUsage()
 {
@@ -35,13 +82,8 @@ HELPDESCRIPTION
     echo
     printShortUsage "$1"
     echo
+    getLongUsage ''
     cat <<HELPTEXT
-    --eval		Print the evaluation result instead of the (quoted)
-			eval.
-    --for DEBUGGEE	Target DEBUGGEE; by default it will take the name of the
-			parent process.
-    --module|-m MODULE	Activate only if debugging for MODULE of the DEBUGGEE is
-			enabled.
 SEE ALSO:
 - inboxtrace duplicates to the inbox location instead of standard error.
 HELPTEXT
@@ -65,6 +107,11 @@ while [ $# -ne 0 ]
 do
     case "$1" in
 	--help|-h|-\?)	shift; printLongUsage "$0"; exit 0;;
+	--get-short-usage)
+			shift; getShortUsage "$@"; exit $?;;
+	--get-long-usage)
+			shift; getLongUsage "$@"; exit $?;;
+
 	--for)		shift; debuggee="${1?}"; shift;;
 	--module|-m)	shift; module="${1:?}"; shift;;
 	--eval)		shift
diff --git a/bin/verbose b/bin/verbose
--- a/bin/verbose
+++ b/bin/verbose
@@ -6,15 +6,113 @@ shopt -qs extglob
 
 readonly scriptName="$(basename -- "${BASH_SOURCE[0]}")"
 
+getShortUsage()
+{
+    local usageSep
+    [ $# -gt 0 ] || set -- ''
+    while [ $# -gt 0 ]
+    do
+	local hadTopic=
+	case "$1" in
+	    ''|general) printf %s "${usageSep}${hadTopic:+ }" '[--eval]'; hadTopic=t;;&
+	    ''|io)
+		printf %s "${usageSep}${hadTopic:+ }" '[-0|--stdin] [-1|--stdout] [-2|--stderr]'; hadTopic=t;;&
+	    ''|debug)
+		[ -n "$1" ] \
+		    && local format='%s%s' \
+		    || local format='%s[%s]'
+		printf "$format" "${usageSep}${hadTopic:+ }" '-D|--on-debug [--for DEBUGGEE] [-m|--module MODULE]'; hadTopic=t;;&
+	    ''|debug-io)
+		printf %s "${usageSep}${hadTopic:+ }" '[--io-modules | [--stdin-module MODULE] [--stdout-module MODULE] [--stderr-module MODULE]]'; hadTopic=t;;&
+	    *)  [ "$hadTopic" ] || { echo "ERROR: Unknown short usage topic \"$1\"!" >&2; return 2; };;
+	esac
+	shift; usageSep=' '
+    done
+}
+getLongUsage()
+{
+    [ $# -gt 0 ] || set -- ''
+    while [ $# -gt 0 ]
+    do
+	local topic="$1"; shift
+	local hadTopic=
+	case "$topic" in
+	    ''|general)
+		cat <<HELPTEXT
+    --eval		Print the evaluation result instead of the (quoted)
+			eval.
+HELPTEXT
+		hadTopic=t
+		;;&
+	    ''|io)
+		cat <<HELPTEXT
+    --stdin|-0		Print standard input (prefixed by 0: if more than one
+			input-output option is active).
+    --stdout|-1		Print standard output (prefixed by 1: if more than one
+			input-output option is active). Without debugging, this
+			only makes sense in combination with -2|--stderr, to see
+			what output came from where.
+    --stderr|-2		Print standard error output (prefixed by 2: if more than
+			one input-output option is active). Without debugging,
+			this only makes sense in combination with -1|--stdout,
+			to see what output came from where.
+HELPTEXT
+		hadTopic=t
+		;;&
+	    ''|debug)
+		cat <<HELPTEXT
+    --on-debug|-D	Log the execution trace to a debug file (DEBUGGEE.log)
+			only when \$DEBUG refers to the DEBUGGEE, and print the
+			debug filespec to the terminal.
+			Else, the COMMAND is just executed as if verbose weren't
+			prepended.
+$ DEBUG=DEBUGGEE[:MODULE] DEBUGGEE ...
+$ DEBUG=debug|${scriptName}=FILE,DEBUGGEE[:MODULE] DEBUGGEE ... will log to a custom
+  FILE instead.
+$ DEBUG=debug|${scriptName} DEBUGGEE ... will show for what DEBUGGEE it will enable
+  (if not actually enabled).
+    --for DEBUGGEE	Target DEBUGGEE; by default it will take the name of the
+			parent process.
+    --module|-m MODULE	Activate only if debugging for MODULE of the DEBUGGEE is
+			enabled.
+HELPTEXT
+		hadTopic=t
+		;;&
+	    ''|debug-io)
+		cat <<HELPTEXT
+    --io-modules	Activate standard input / output / error logging only if
+			debugging for module "input" / "output" / "errors" of
+			the DEBUGGEE is enabled.
+			Syntactic sugar for --stdin-module input \\
+			    --stdout-module output --stderr-module errors
+    --stdin-module MODULE
+			Log standard input (prefixed by 0: if more than one
+			input-output option is active) only if debugging for
+			MODULE of the DEBUGGEE is enabled.
+    --stdout-module MODULE
+			Log standard output (prefixed by 1: if more than one
+			input-output option is active) only if debugging for
+			MODULE of the DEBUGGEE is enabled.
+    --stderr-module MODULE
+			Log standard error output (prefixed by 2: if more than
+			one input-output option is active) only if debugging for
+			MODULE of the DEBUGGEE is enabled.
+HELPTEXT
+		hadTopic=t
+		;;&
+	    *)  [ "$hadTopic" ] || { echo "ERROR: Unknown long usage topic \"$topic\"!" >&2; return 2; };;
+	esac
+    done
+}
 printShortUsage()
 {
     # Note: short followed by long option; if the user knows the short one, she can
     # skim the long one.
-    printf 'Usage: [VERBOSE_IFS=STRING|newline] [VERBOSE_SINK=FILESPEC|&N] %q %s\n' "$(basename "$1")" '[--eval] [-0|--stdin] [-1|--stdout] [-2|--stderr] [-?|-h|--help] ...'
+    printf 'Usage: [VERBOSE_IFS=STRING|newline] [VERBOSE_SINK=FILESPEC|&N] %q %s\n' "$(basename "$1")" "$(getShortUsage general) $(getShortUsage io) [-?|-h|--help] ..."
     echo
     printf 'Usage: %q %s\n' "$(basename "$1")" '... [--] COMMAND [ARG ...]'
     echo
-    printf 'Usage: ${DEBUG:+[env VERBOSE_IFS=STRING|newline] [[VERBOSE|DEBUG]_SINK=FILESPEC|&N] %q %s} %s\n' "$(basename "$1")" '... -D|--on-debug [--for DEBUGGEE] [-m|--module MODULE] [--io-modules | [--stdin-module MODULE] [--stdout-module MODULE] [--stderr-module MODULE]] [--]' 'COMMAND [ARG ...]'
+    printf 'Usage: ${DEBUG:+[env VERBOSE_IFS=STRING|newline] [[VERBOSE|DEBUG]_SINK=FILESPEC|&N] %q %s} %s\n' "$(basename "$1")" "... $(getShortUsage debug) $(getShortUsage debug-io) [--]" 'COMMAND [ARG ...]'
 }
 printUsage()
 {
@@ -35,50 +133,8 @@ HELPDESCRIPTION
     echo
     printShortUsage "$1"
     echo
+    getLongUsage ''
     cat <<HELPTEXT
-    --eval		Print the evaluation result instead of the (quoted)
-			eval.
-    --stdin|-0		Print standard input (prefixed by 0: if more than one
-			input-output option is active).
-    --stdout|-1		Print standard output (prefixed by 1: if more than one
-			input-output option is active). Without debugging, this
-			only makes sense in combination with -2|--stderr, to see
-			what output came from where.
-    --stderr|-2		Print standard error output (prefixed by 2: if more than
-			one input-output option is active). Without debugging,
-			this only makes sense in combination with -1|--stdout,
-			to see what output came from where.
-    --on-debug|-D	Log the execution trace to a debug file (DEBUGGEE.log)
-			only when \$DEBUG refers to the DEBUGGEE, and print the
-			debug filespec to the terminal.
-			Else, the COMMAND is just executed as if verbose weren't
-			prepended.
-$ DEBUG=DEBUGGEE[:MODULE] DEBUGGEE ...
-$ DEBUG=debug|${scriptName}=FILE,DEBUGGEE[:MODULE] DEBUGGEE ... will log to a custom
-  FILE instead.
-$ DEBUG=debug|${scriptName} DEBUGGEE ... will show for what DEBUGGEE it will enable
-  (if not actually enabled).
-    --for DEBUGGEE	Target DEBUGGEE; by default it will take the name of the
-			parent process.
-    --module|-m MODULE	Activate only if debugging for MODULE of the DEBUGGEE is
-			enabled.
-    --io-modules	Activate standard input / output / error logging only if
-			debugging for module "input" / "output" / "errors" of
-			the DEBUGGEE is enabled.
-			Syntactic sugar for --stdin-module input \\
-			    --stdout-module output --stderr-module errors
-    --stdin-module MODULE
-			Log standard input (prefixed by 0: if more than one
-			input-output option is active) only if debugging for
-			MODULE of the DEBUGGEE is enabled.
-    --stdout-module MODULE
-			Log standard output (prefixed by 1: if more than one
-			input-output option is active) only if debugging for
-			MODULE of the DEBUGGEE is enabled.
-    --stderr-module MODULE
-			Log standard error output (prefixed by 2: if more than
-			one input-output option is active) only if debugging for
-			MODULE of the DEBUGGEE is enabled.
 SEE ALSO:
 - dump-args-exec also prints command-line arguments (without nesting level), and
   can prepend an argument count or use array syntax, but is more geared toward
@@ -120,6 +176,11 @@ while [ $# -ne 0 ]
 do
     case "$1" in
 	--help|-h|-\?)	shift; printLongUsage "$0"; exit 0;;
+	--get-short-usage)
+			shift; getShortUsage "$@"; exit $?;;
+	--get-long-usage)
+			shift; getLongUsage "$@"; exit $?;;
+
 	--stdin|-0)	shift; logFileDescriptors[0]+=t;;
 	--stdout|-1)	shift; logFileDescriptors[1]+=t;;
 	--stderr|-2)	shift; logFileDescriptors[2]+=t;;
