verbose: CHG: Turn --on-debug KEYWORD into --on-debug, rename VERBOSE_TRACEFILE to VERBOSE_SINK
System-info: Ubuntu 20.04.6 LTS, x86_64
Platform-info: bash 5.0.17(1)-release

diff --git a/bin/verbose b/bin/verbose
--- a/bin/verbose
+++ b/bin/verbose
@@ -1,15 +1,16 @@
 #!/bin/bash
+shopt -qs extglob
 
 : ${VERBOSE_IFS=' '}
 [ "$VERBOSE_IFS" = newline ] && VERBOSE_IFS=$' \\\n  '
+
+readonly scriptName="$(basename -- "${BASH_SOURCE[0]}")"
 
 printShortUsage()
 {
     # Note: short followed by long option; if the user knows the short one, she can
     # skim the long one.
-    printf 'Usage: [VERBOSE_IFS=STRING|newline] [VERBOSE_TRACEFILE=FILESPEC|&N] %q %s\n' "$(basename "$1")" '[--eval] [--] [SIMPLECOMMAND ...] [-?|-h|--help]'
-    echo
-    printf 'Usage: [VERBOSE_IFS=STRING|newline] [VERBOSE_TRACEFILE=FILESPEC|&N] ${DEBUG:+%q %s} %s\n' "$(basename "$1")" '-D|--on-debug KEYWORD' '[...] [--] [SIMPLECOMMAND ...]'
+    printf 'Usage: [VERBOSE_IFS=STRING|newline] [VERBOSE_SINK=FILESPEC|&N] %q %s\n' "$(basename "$1")" '[--eval] [-D|--on-debug [--for DEBUGGEE] [-m|--module MODULE]] [--] COMMAND [ARG ...] [-?|-h|--help]'
 }
 printUsage()
 {
@@ -25,18 +26,26 @@ printLongUsage()
     cat <<HELPDESCRIPTION
 Execute and write arguments (separated by a space or \$VERBOSE_IFS) as an
 execution trace (i.e. with \$PS4 prepended and indicating the nesting level) to
-standard error / \$VERBOSE_TRACEFILE, just like "set -x".
+standard error / \$VERBOSE_SINK, just like "set -x".
 HELPDESCRIPTION
     echo
     printShortUsage "$1"
     echo
     cat <<HELPTEXT
-    --on-debug|-D KEYWORD
-			Only print the execution trace when \$DEBUG contains
-			KEYWORD. Else, the COMMAND is just executed as if
-			verbose weren't prepended.
     --eval		Print the evaluation result instead of the (quoted)
 			eval.
+    --on-debug|-D	Only print the execution trace when \$DEBUG refers to
+			the DEBUGGEE. Else, the COMMAND is just executed as if
+			verbose weren't prepended.
+$ DEBUG=DEBUGGEE[:MODULE] DEBUGGEE ...
+$ DEBUG=debug|${scriptName}=FILE,DEBUGGEE[:MODULE] DEBUGGEE ... will log to a custom
+  FILE instead.
+$ DEBUG=debug|${scriptName} DEBUGGEE ... will show for what DEBUGGEE it will enable (if not
+  actually enabled).
+    --for DEBUGGEE	Target DEBUGGEE; by default it will take the name of the
+			parent process.
+    --module|-m MODULE	Activate only if debugging for MODULE of the DEBUGGEE is
+			enabled.
 HELPTEXT
 }
 
@@ -48,17 +57,21 @@ printer()
 }
 executor()
 {
-    [ "$1" = eval ] && EXEC=''
     $EXEC "$@"
 }
 
 EXEC=exec
 isActive=t
+isOnDebug=
+debuggee=
+module=
 while [ $# -ne 0 ]
 do
     case "$1" in
 	--help|-h|-\?)	shift; printLongUsage "$0"; exit 0;;
-	--on-debug|-D)	shift; case ",${DEBUG:-}," in *,${1:?},*) ;; *) isActive=;; esac; shift;;
+	--on-debug|-D)	shift; isOnDebug=t; isActive=;;
+	--for)		shift; debuggee="${1?}"; shift;;
+	--module|-m)	shift; module="${1:?}"; shift;;
 	--eval)		shift
 			if [ "$1" = eval ]; then
 			    shift
@@ -77,13 +90,44 @@ do
 	*)		break;;
     esac
 done
-[ $# -eq 0 ] && exit
+if [ $# -eq 0 ]; then
+    echo >&2 'ERROR: No COMMAND passed.'
+    echo >&2
+    printUsage "$0" >&2
+    exit 2
+fi
+
+if [ "$isOnDebug" ] && [ -n "$DEBUG" ]; then
+    if [ -z "$debuggee" ]; then
+	{
+	    IFS= read -r -d '' debugCmd
+	    IFS= read -r -d '' debugSecond
+	} < /proc/${DUMPARGS_PPID:-$PPID}/cmdline
+	debuggee="$(commandName --no-interpreter --undefined "$scriptName" -- "$debugCmd" "$debugSecond")"
+    fi
+
+    case ",${DEBUG:-}," in
+	*,${debuggee}${module:+:}${module},*)
+	    case ",${DEBUG:-}," in
+		*,@(debug|${scriptName})=*,*)
+		    VERBOSE_SINK=",${DEBUG},"; VERBOSE_SINK="${VERBOSE_SINK#*,@(debug|${scriptName})=}"; VERBOSE_SINK="${VERBOSE_SINK%%,*}"
+		    ;;
+		*)  : ${VERBOSE_SINK:="${PWD}/${debuggee//:/-}.log"};;
+	    esac
+	    isActive=t
+	    EXEC=''
+	    ;;
+	*,@(debug|${scriptName}),*)
+	    printf >&2 '%s: Will activate with DEBUG=%q\n' "$scriptName" "${debuggee}${module:+:}${module}"
+	    ;;
+    esac
+fi
 
 if [ "$isActive" ]; then
-    case "$VERBOSE_TRACEFILE" in
+    case "$VERBOSE_SINK" in
 	'')		exec 3>&2;;
-	\&[0-9])	eval "exec 3>$VERBOSE_TRACEFILE";;
-	?*)		exec 3>>"$VERBOSE_TRACEFILE";;
+	\&[0-9])	eval "exec 3>$VERBOSE_SINK";;
+	?*)		exec 3>>"$VERBOSE_SINK";;
     esac
 
     # Duplicated to echotrace
@@ -99,4 +143,8 @@ if [ "$isActive" ]; then
     printer "$@"
 fi
 
-executor "$@"
+executor "$@"; status=$?
+if [ "$isOnDebug" ] && [ -n "$VERBOSE_SINK" ]; then
+    printf >&2 "%s%s invocation logged to %q\\n" "$PS4" "$scriptName" "$VERBOSE_SINK"
+fi
+exit $status
