ENH: Check for debugtrace support and use a subshell with set -x and source to externally enable it if COMMAND has no built-in support
Taking over the hasTraceSupport() function and external enabling from the trace command.

System-info: Ubuntu 20.04.6 LTS, x86_64
Platform-info: bash 5.0.17(1)-release

diff --git a/bin/withDebug b/bin/withDebug
--- a/bin/withDebug
+++ b/bin/withDebug
@@ -108,12 +108,19 @@ addDebug()
     done
 }
 
+hasTraceSupport()
+{
+    local commandFilespec="${1:?}"; shift
+    grep --quiet \
+	    -e '\${DEBUG:+eval \$(\(DEBUG[^[:space:]]\+[[:space:]]\+\)\?debugtrace[[:space:]]' \
+	    -- "$commandFilespec"
+}
 commands=
 addCommand()
 {
     local cmd="${1:?}"; shift
 
-    local wrappers='' commandName
+    local wrappers='' commandName isTraceCommand
     for commandName in "${commandNames[@]}"
     do
 	local module; for module in "${modules[@]}"
@@ -124,7 +131,23 @@ addCommand()
 		wrappers+="${!wrapperConfigName} "
 	    fi
 	done
+
+	[ "$extension" = "&${commandName}" ] && isTraceCommand=t
     done
+
+    if [ "$extension" = '&' ] || [ "$isTraceCommand" ]; then
+	local commandFilespec="$(COMMANDNAME_WRAPPERS='' commandName --no-interpreter --full-filespec --eval "$cmd")"
+	if [ -n "$commandFilespec" ] \
+	    && [ -r "$commandFilespec" ] \
+	    && ! hasTraceSupport "$commandFilespec"
+	then
+	    if [ -n "$wrappers" ]; then
+		printf >&2 'Note: Cannot enable tracing for %s without built-in debugtrace support when a wrapper is configured.\n' "$commandFilespec"
+	    else
+		printf -v cmd '(BASH_ARGV0=%q; set -x; . %s)' "$commandFilespec" "$cmd"
+	    fi
+	fi
+    fi
 
     commands+="${commands:+ $WITHDEBUG_COMMAND_JOINER }${wrappers}${cmd}"
 }
