withDebug: ENH: Introduce DEBUG_LOGDIR, default to /run/user/$UID/debug, and only fall back to $PWD if explicitly empty
So any debug logs are now by default collected in a dedicated directory, instead of cluttering the PWDs of all instrumented executions.

System-info: Ubuntu 20.04.6 LTS, x86_64
Platform-info: bash 5.0.17(1)-release

diff --git a/bin/withDebug b/bin/withDebug
--- a/bin/withDebug
+++ b/bin/withDebug
@@ -9,6 +9,10 @@ readonly WITHDEBUG_RECALL_FILESPEC="${DATA_DIRSPEC}/withDebug-recall"
 readonly WITHDEBUG_SAME_FILESPEC="${DATA_DIRSPEC}/withDebug-same"
 readonly WITHDEBUG_LASTLOG_FILESPEC="${DATA_DIRSPEC}/withDebug-last-log"
 
+: ${DEBUG_LOGDIR="${XDG_RUNTIME_DIR:-/tmp}/debug"}; export DEBUG_LOGDIR
+[ -z "$DEBUG_LOGDIR" -o -d "$DEBUG_LOGDIR" ] || mkdir --parents -- "$DEBUG_LOGDIR" || { printf >&2 'ERROR: Could not initialize default log directory at %s\n' "$DEBUG_LOGDIR"; exit 3; }
+defaultLogDirspec="${DEBUG_LOGDIR-$PWD}"
+
 printShortUsage()
 {
     # Note: short followed by long option; if the user knows the short one, she can
@@ -46,7 +50,8 @@ HELPDESCRIPTION
     --no-pager|-P	Don't open the debugging diagnostics in the pager after
 			the execution.
     --to FILE		Write the debugging diagnostics into FILE instead of the
-			default COMMAND.log (using the first passed COMMAND).
+			default COMMAND.log (using the first passed COMMAND) in
+			\$DEBUG_LOGDIR (${DEBUG_LOGDIR}).
     --inbox|-i		Write the debugging diagnostics into the inbox.
     --to-separate-files|-s
 			Let each COMMAND write its debugging diagnostics into a
@@ -507,9 +512,9 @@ if [ -n "$programName" ]; then
     if [ "$isInteractive" ]; then
 	printf -v commands 'bash -i -c %q' "$commands"
     fi
-    : ${sink="${PWD}/${programName}.log"}
+    : ${sink="${defaultLogDirspec}${defaultLogDirspec:+/}${programName}.log"}
 else
-    : ${sink="${PWD}/${commandNames[0]:?}.log"}
+    : ${sink="${defaultLogDirspec}${defaultLogDirspec:+/}${commandNames[0]:?}.log"}
 fi
 
 if [ ${#captureCommand[@]} -gt 0 ]; then
